instance_activate_object(obj_menu_logo);
instance_activate_object(obj_play_button);
instance_activate_object(obj_level_selector_button);
instance_activate_object(obj_quit_button);
instance_activate_object(obj_instructions);

instance_destroy(obj_choose_level_button);
instance_destroy();